name: tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  test-configs:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: brokeyourbike/ocvalidate-action@v0.2
        with:
          opencore-version: '0.7.8'
          release: true

      - run: |
          ocvalidate "EFI/OC/config.plist" || exit 1
          ocvalidate "EFI/OC/config-2643V2.plist" || exit 1
          ocvalidate "EFI/OC/config-2667V2.plist" || exit 1
          ocvalidate "EFI/OC/config-2687V2.plist" || exit 1